// <auto-generated />
using System;
using HealthBot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthBot.Infrastructure.Migrations
{
    [DbContext(typeof(HealthBotDbContext))]
    [Migration("20251108172524_ConversationSessions")]
    partial class ConversationSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthBot.Core.Entities.ConversationSession", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<string>("CustomMessage")
                        .HasColumnType("text")
                        .HasColumnName("custom_message");

                    b.Property<bool>("ExpectManualInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("expect_manual_input");

                    b.Property<int?>("FirstDelayMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("first_delay_minutes");

                    b.Property<int>("Flow")
                        .HasColumnType("integer")
                        .HasColumnName("flow");

                    b.Property<int?>("LastBotMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("last_bot_message_id");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<string>("TemplateCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("template_code");

                    b.Property<int?>("TemplateDefaultRepeat")
                        .HasColumnType("integer")
                        .HasColumnName("template_default_repeat");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("TemplateTitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("template_title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("ChatId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("conversation_sessions", (string)null);
                });

            modelBuilder.Entity("HealthBot.Core.Entities.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NextTriggerAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RepeatIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NextTriggerAt");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("reminders", (string)null);
                });

            modelBuilder.Entity("HealthBot.Core.Entities.ReminderTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("DefaultRepeatIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("reminder_templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3c63a05-3cb3-4dd0-a6a5-8f3483c962dd"),
                            Code = "stretch",
                            DefaultRepeatIntervalMinutes = 60,
                            Description = "Короткая разминка, чтобы размять мышцы.",
                            IsSystem = true,
                            Title = "Размяться, хватит сидеть"
                        },
                        new
                        {
                            Id = new Guid("a6df40eb-8138-4949-9305-1c9458c7bf57"),
                            Code = "drink",
                            DefaultRepeatIntervalMinutes = 45,
                            Description = "Напоминание сделать паузу и выпить воды.",
                            IsSystem = true,
                            Title = "Попей воды!"
                        },
                        new
                        {
                            Id = new Guid("4a9df57a-3958-4e32-9b6d-3f5e6f5729fd"),
                            Code = "eat",
                            DefaultRepeatIntervalMinutes = 180,
                            Description = "Своевременный перекус или обед.",
                            IsSystem = true,
                            Title = "Покушай"
                        });
                });

            modelBuilder.Entity("HealthBot.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HealthBot.Core.Entities.Reminder", b =>
                {
                    b.HasOne("HealthBot.Core.Entities.ReminderTemplate", "Template")
                        .WithMany("Reminders")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealthBot.Core.Entities.User", "User")
                        .WithMany("Reminders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthBot.Core.Entities.ReminderTemplate", b =>
                {
                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("HealthBot.Core.Entities.User", b =>
                {
                    b.Navigation("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
